### ISSUE TITLE
Doesnt follow symlinks from music directory

### ISSUE THREAD

**Issue by monolied** [rbackhouse/MaximumMPD#1]
Subject says all, I guess. I have (lots of) symlinks in the music directory. Most mpd clients follow these and offer those too; MaximumMPD (and a handful others) don't.
I only tried with the iOS version. Seems like a decent app otherwise, but I didn't use it much for that reason.

**Comment by rbackhouse** [comment]
Its seems the "listfiles" command I'm using does not return symlinks. The "lsinfo" command does appear to though. I'll look into using that if possible.

Thanks for the report

**Comment by rbackhouse** [comment]
Available in the 1.2 Release now available
