### ISSUE TITLE
search doesn't return all results

### ISSUE THREAD

**Issue by guestguestguestguest** [rbackhouse/MaximumMPD#106]
When I enter the word "Stand" in the Search input field, the song 'Stand' by R.E.M. is not included in the results.  But it is on my server and is listed by Browse.
![7269](https://github.com/rbackhouse/MaximumMPD/assets/49593951/8e48eeee-4b76-43c6-9fc5-757193453e9a)
![7268](https://github.com/rbackhouse/MaximumMPD/assets/49593951/d7955ead-5389-45e5-952f-a41300408519)
![7267](https://github.com/rbackhouse/MaximumMPD/assets/49593951/bf516a41-07fb-4730-a91f-45e1cb1c58bd)
![7266](https://github.com/rbackhouse/MaximumMPD/assets/49593951/72230b64-ef40-4df2-92f1-1d526b2c5584)
![7265](https://github.com/rbackhouse/MaximumMPD/assets/49593951/562b9497-b030-42f4-a106-56d184bf21d0)

**Comment by guestguestguestguest** [comment]
Music Player Daemon 0.21.23 (0.21.23)
Maximum MPD version 5.7

**Comment by rbackhouse** [comment]
I suspect this to due to a limit on the number items returned for a search. It is set for 50 and there is no priority set for exact matches. 

It should really make sure exact matches are listed first and i would expect that would fix this scenario you are seeing.

**Comment by guestguestguestguest** [comment]
That makes sense.  I agree that listing exact matches first would fix this.  And maybe make the max search returns a settable configuration option, although 50 does seem quite reasonable for most cases.

**Comment by rbackhouse** [comment]
Version 5.8 now in the App Store should have a fix for this

**Comment by guestguestguestguest** [comment]
Thanks Richard. It doesn't appear in the App Store on my phone yet but I will install the update once I see it listed.

Frank

------- Original Message -------

**Comment by guestguestguestguest** [comment]
Hi Richard,

I just installed MaximumMPD 5.8 and I'm sad to report that the exact same use case still fails (search results for "Stand" does not list the song "Stand" by R.E.M.).

Frank

------- Original Message -------

**Comment by rbackhouse** [comment]
Are you seeing the same order of songs returned as before or is it different ?

**Comment by rbackhouse** [comment]
Ok, that suggests the the priority on the exact match for 'stand' is working but my guess is that the 50 limit is excluding it from the initial search results and never gets prioritized. I could make the search results limit configurable but I think I need to look into a better solution.

**Comment by rbackhouse** [comment]
I've got a new version in the app store that should hopefully fix the problem. The search function now perform 2 searches, the first looks for exact title matches and the second as it was previously. This should ensure that exact title matches show up first in the "Songs" section

**Comment by guestguestguestguest** [comment]
Fixed. Thanks Richard!

------- Original Message -------
