### ISSUE TITLE
searching for artist name containing single quote fails

### ISSUE THREAD

**Issue by guestguestguestguest** [rbackhouse/MaximumMPD#109]
On the Browse Artists screen, searching for "It's A Beautiful Day" returns no results.  This is a valid artist name in the database.  I tried bare as well as enclosing with double-quotes.

**Comment by rbackhouse** [comment]
This is a problem with unicode single quotes. They come in from the search bar as left and right ones so I'll have to convert them to asciii

**Comment by rbackhouse** [comment]
Should be fixed in Version 6.3 now in the App Store

**Comment by guestguestguestguest** [comment]
Perfect.  Thanks Richard.
