### ISSUE TITLE
Stripping trailing spaces off MPD response lines can cause artist and album tags to be incorrectly processed

### ISSUE THREAD

**Issue by rbackhouse** [rbackhouse/MaximumMPD#110]

**Comment by rbackhouse** [comment]
[part-aa.zip](https://github.com/rbackhouse/MaximumMPD/files/14233050/part-aa.zip)
[part-ab.zip](https://github.com/rbackhouse/MaximumMPD/files/14233052/part-ab.zip)

**Comment by guestguestguestguest** [comment]
split flac file 1: led zeppelin track  'good times bad times'
[lz-gtbtad.zip](https://github.com/rbackhouse/MaximumMPD/files/14234111/lz-gtbtad.zip)
[lz-gtbtac.zip](https://github.com/rbackhouse/MaximumMPD/files/14234112/lz-gtbtac.zip)
[lz-gtbtab.zip](https://github.com/rbackhouse/MaximumMPD/files/14234114/lz-gtbtab.zip)
[lz-gtbtaa.zip](https://github.com/rbackhouse/MaximumMPD/files/14234115/lz-gtbtaa.zip)

**Comment by guestguestguestguest** [comment]
Split flac file 2: michael brecker track 'talking to myself'
[mb-t2mab.zip](https://github.com/rbackhouse/MaximumMPD/files/14234120/mb-t2mab.zip)
[mb-t2maa.zip](https://github.com/rbackhouse/MaximumMPD/files/14234121/mb-t2maa.zip)

**Comment by rbackhouse** [comment]
Version 6.4 in the App Store should have a fix for this
