### ISSUE TITLE
save queue as playlist

### ISSUE THREAD

**Issue by guestguestguestguest** [rbackhouse/MaximumMPD#12]
New feature request: after creating a random playlist in the queue, I would like to be able to save it to the playlists for future use.  Thanks for your consideration.

**Comment by rbackhouse** [comment]
I can add a new action button to the Playlists tab that will create a playlist from the current queue. The name of the playlist will be prompted for. If the playlist already exists then the current queue will just be added to it

**Comment by guestguestguestguest** [comment]
Sounds perfect, thanks Richard.

**Comment by rbackhouse** [comment]
Available in Version 1.9
