### ISSUE TITLE
Files disappear under File View after a short time

### ISSUE THREAD

**Issue by ed76** [rbackhouse/MaximumMPD#14]
hi richard,

i have tested your app for a few days and think it is very good! the app is lightweight, fast and looks very good.

i have a problem and and a feature request.

problem: after a connection to the mpd server all folders and files are present in the “file view”, i can play the files too. after a short time only the folders are displayed under the “file view”, but no more files. the folders are empty. however, via album view or artist view everything works permanently as it should (mp3s are recognized). is that a bug?

feature request to improve everyday use (especially for my wife :-) )

1. is it possible that the app automatically connects to the mpd-server at startup?
2. would it be possible to add a "play-button" to each folder/album/playlist that does the following: clear queue, add content of folder/album/playlist to queue and automatically play first song? maybe as an option?

**Comment by rbackhouse** [comment]
It does sound like a bug. It might be to do with a disconnect and reconnect that the app will attempt if the connection is lost. It tries to clean current info and may not be doing that correctly in the files view. I’ll see if I can recreate.

Those enhancement requests seem reasonable. I’ll create separate issue reports for them.

**Comment by ed76** [comment]
That sounds good! Thank you very much!

One last question: To get AlbumArt you have to activate this in the settings of maximum mpd. Furthermore your mpd server version must be > 0.21 and you must have a “folder.jpg” within album folder. Is this all or is there anything else i have to configure (maybe mpd server)?

**Comment by rbackhouse** [comment]
The MPD server requires that the filename must be cover.png, cover.jpg, cover.tiff or cover.bmp. And version of MPD must 0.21 or greater

**Comment by ed76** [comment]
Thank you! It's working now.

**Comment by rbackhouse** [comment]
Hmm I haven't released anything new. So not sure what solved the issue

**Comment by ed76** [comment]
oh, that was a misunderstanding...
i only mean the album art. after renaming folder.jpg to cover.jpg the covers are displayed now within your ios app. the other problem persists. sorry for the confusion.

**Comment by rbackhouse** [comment]
Should be fixed in Version 2.0 in the App Store.

**Comment by ed76** [comment]
thanks!
