### ISSUE TITLE
Album art down load Issues

### ISSUE THREAD

**Issue by epicfrequency** [rbackhouse/MaximumMPD#17]
1) Album arts download hangs time to time
2) Broken picture , seems more often on large album art files

**Comment by rbackhouse** [comment]
Can you send me an example of a album image file that you are having a problem with. Send it to richardabackhouse@gmail.com

Also can you provide more detail on the problems ? Does it seem to be always on the same image files ?

**Comment by epicfrequency** [comment]
Image sent for problem 2. 
For 1, the image download will stop for no reason.

**Comment by rbackhouse** [comment]
I'm not seeing any problems with the image you sent. My guess is that the download did not complete for some reason and left the image corrupted. 

All the downloaded album covers are stored in a directory accessible via the iOS Files app. You can find them in a directory called MaximumMPD/mpd_album_art. If you find the broken image in there you can delete it and MaximumMPD will attempt to download it again.

As far as the hanging goes I think it best for me to add some debug logging support to the app to try and gain more insight into what's going on.  The code attempt to download when the MPD server is idle so as to not overwhelm it with albumart requests however this means it can take a very long time to download from scratch. I may rethink the current approach.

**Comment by epicfrequency** [comment]
I think I have duplicated a few hang ups because of the image file being too big, like more than 4Mb files. Seems there is no album cover file size check. MaximumMPD will try to get a very big cover file and stuck. Maybe that's the reason.

**Comment by epicfrequency** [comment]
Now after looking into it, even small files like 500kB cover file will get it stuck, seems there is no timeout etc, it just stuck

**Comment by rbackhouse** [comment]
TBH the albumart API in MPD is not really going to work speedily with large albumart files. It doesn't  provide a true streaming API. The MPD server decides the chunk size and from what I have seen that is typically 8k. For a 512k file that will be 64 calls for a single file.

I think it would be best to implement a max size option. The API does provide the total size on each request so can be aborted ob the first request if the size is too big.

**Comment by epicfrequency** [comment]
I changed MPD source code  MAX_BINARY_BUFFER from 8129 to 1048576, previous broken or stuck album art down load problems are gone.  I guess MPD's binary buffer size is too small, will issue a pull in MPD repo to see if they can fix it.

**Comment by rbackhouse** [comment]
I've tried testing with a number of very large files (The largest was 11mb) and they all downloaded eventually. They just took a very long time.

I'm going to add file size and percentage downloaded information to the AlbumArt settings page so that it will be apparent if a hang has occurred.

**Comment by rbackhouse** [comment]
File size and percentage downloaded information is now available in Version 2.0 in the App Store

**Comment by rbackhouse** [comment]
I'm going to close this for now. Please reopen if you have more information on recreating
