### ISSUE TITLE
browse bug

### ISSUE THREAD

**Issue by guestguestguestguest** [rbackhouse/MaximumMPD#2]
![maxMpdBrowseScreen](https://user-images.githubusercontent.com/49593951/56082774-afc54580-5dd1-11e9-80c0-0f204f2d6e56.PNG)
Browsing artists on iOS 12.2 MaximumMPD version 1.3 goes crazy displaying 95 duplicate entries for  Dvořák, Antonin.  Sorted alphabetically, all artists up to this one are listed properly, then it appears to loop on this artist, then it moves the 95 duplicate entries to the top of the list, then when browsing below Dvořák, Antonin it appears to add yet more duplicate entries for this one.

**Comment by rbackhouse** [comment]
Should be resolved with the 1.4 release

**Comment by guestguestguestguest** [comment]
Thanks for the fix Richard.  Looks good.  FYI version 1.4 does not appear in the App Store's 'updates' list [for installed apps], and MaximumMPD does not show up in a search for 'MPD' in the App Store.  I had to find it by selecting MPD js and then clicking 'other apps by this author'.

I understand it's a lot of work and you're busy, but a couple of features on my wish list for future versions are:

1. Browse by genre
2. When an artist name begins with the word 'The', use the following word when sorting

Thanks again for a useable MPD client!

Frank

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by rbackhouse** [comment]
That's weird on not showing in "updates" yet. Perhaps it hadn't trickled through yet.

I've opened up a couple of enhancement for your feature requests

https://github.com/rbackhouse/MaximumMPD/issues/3
https://github.com/rbackhouse/MaximumMPD/issues/4

I'll look to get them in the next release

**Comment by guestguestguestguest** [comment]
Hi Richard,

I downloaded your new version of MaximumMPD today.  Thanks much for adding my feature requests.  This makes me happy to see.

I would prefer if the items listed when browsing a genre were albums rather than individual songs, which you could drill down to browse underneath...making it easier to view and add an album to the queue or playlist.

But of course I'm just another user wanting more more more.  You are doing all the work.  I am not an insatiable beast asking for feature after feature.  Please just consider the idea for whenever you have time to spend on it.

I'm happy you continue to enhance this app.  And I'm happy that you put the code on github.  I cloned it and will try to find some time to examine AlbumArt.js to see if I can identify the section which populates genre lists.  And maybe dink around a bit.

Cheers from Seattle,
Frank

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by guestguestguestguest** [comment]
Sorry to say I found a bug when browsing Albums: the artist listed is for the prior album in the list [an "off-by-one error" in matching up artist to album].  Screenshot demonstrating the error:

![mmpd-albums-screenshot](https://user-images.githubusercontent.com/49593951/61847689-74babf80-ae60-11e9-82db-2493044e8a1d.png)

**Comment by rbackhouse** [comment]
I should be able add a config option allowing for either songs or albums to be the result of a genre selection. I’ll create an Enhancement ticket for it

Richard

**Comment by rbackhouse** [comment]
Ok I’ll take a look

I’ve opened a bug issue for it

https://github.com/rbackhouse/MaximumMPD/issues/7 <https://github.com/rbackhouse/MaximumMPD/issues/7>
