### ISSUE TITLE
crash when playing online radio stream/playlist

### ISSUE THREAD

**Issue by ed76** [rbackhouse/MaximumMPD#20]
new version 2.1 crashes when playing online radio via playlist. after you start the stream everything is ok. but once you activate the „playing“-tab maximummpd crashes. never had this problem with earlier versions.

(and thanks for add the „play-feature“ to maximummpd).

**Comment by rbackhouse** [comment]
Can you provide some detail on the configuration of your radio stream ?

**Comment by rbackhouse** [comment]
Nevermind. I was able to recreate and see what the problem is.

**Comment by rbackhouse** [comment]
Fix available in Version 2.2

**Comment by ed76** [comment]
thank you very much!
