### ISSUE TITLE
MPD volume is set to device volume on start

### ISSUE THREAD

**Issue by davidchisnall** [rbackhouse/MaximumMPD#22]
When MaximumMPD is launched, it appears to set the remote volume to the media volume of the device that it's running on.  It took me a few days to figure out that why my music kept going silent: the volume on my iPad is typically set to around 30%, but on the MPD server anything below about 70% is inaudible.

**Comment by rbackhouse** [comment]
Fixed in version 2.3. The device volume is now set to the currently connected MPD servers volume
