### ISSUE TITLE
Playlist: can't display Extended_M3U tracks info

### ISSUE THREAD

**Issue by macmpi** [rbackhouse/MaximumMPD#29]
Hi,
I've set a few extended [M3U playlist](https://en.wikipedia.org/wiki/M3U#Extended_M3U) on my MPD server, and MaximumMPD only shows file locations (or URLs): I could not find a way to show fancier Title, Artist Name, and al.
Appreciate any help or trick to improve display.

BTW, command-line mpc does show proper info like below:
```
mpd:~$ mpc playlist
CD - Piste 1
CD - Piste 2
CD - Piste 3
CD - Piste 4
CD - Piste 5
CD - Piste 6
CD - Piste 7
CD - Piste 8
CD - Piste 9
CD - Piste 10
CD - Piste 11
```

**Comment by rbackhouse** [comment]
I've not used extended m3u before. Did you have to do anything config wise for your MPD server ? 

I see there is extm3u playlist plugin. I've tried enabling that but don't see any additional tag data being returned when querying the playlist details via MPD.

Also some examples of the extended tags that you use would help too.

**Comment by macmpi** [comment]
Here is a sample playlist that was loaded by `mpc load CD` in previous exemple.
MaximumMPD only shows items as `cdda:///1` & al rather than `CD - Piste 1`
```
mpd:~$ cat /var/lib/mpd/playlists/CD.m3u
#EXTM3U

#EXTINF:0,CD - Piste 1
cdda:///1

#EXTINF:0,CD - Piste 2
cdda:///2

#EXTINF:0,CD - Piste 3
cdda:///3

#EXTINF:0,CD - Piste 4
cdda:///4

#EXTINF:0,CD - Piste 5
cdda:///5

#EXTINF:0,CD - Piste 6
cdda:///6

#EXTINF:0,CD - Piste 7
cdda:///7

#EXTINF:0,CD - Piste 8
cdda:///8

#EXTINF:0,CD - Piste 9
cdda:///9

#EXTINF:0,CD - Piste 10
cdda:///10

#EXTINF:0,CD - Piste 11
cdda:///11
```

**Comment by rbackhouse** [comment]
I can see the extra tag data now. Looking at the source for the MPD ExtM3uPlaylistPlugin it looks like the only tags it adds are "Name" and "duration". I can pulls those into the Playlist Details entries if they are present

**Comment by rbackhouse** [comment]
Available in Version 2.7

**Comment by macmpi** [comment]
Thanks it works great for Playlist / Queue views ! (sorry, I did not have a chance to test earlier)
In Playing view, "fancy name" does not follow though.

**Comment by macmpi** [comment]
...and another thing which can be useful: if duration of actual file does not match the one set in M3U (or other) playlist, then trust actual file

**Comment by rbackhouse** [comment]
I don't think that is going to be doable. It seems MPD pulls the duration/Time from the playlist enty if it's present when adding to the queue. The client would have to then search for the song to compare the durations.

**Comment by rbackhouse** [comment]
The Name should now show on the Playing page and also in queue list items. The duration show also show on the Playlist details page. Available in version 2.9

**Comment by macmpi** [comment]
thanks!

**Comment by macmpi** [comment]
> I don't think that is going to be doable. It seems MPD pulls the duration/Time from the playlist enty if it's present when adding to the queue. The client would have to then search for the song to compare the durations.

Actually, when you start paying tracks with command-line `mpc`, track duration is then properly reported if you check `mpc status`. So info is available for client side during playback (Rigelian also reports it for instance).

UI probably just needs to be refreshed, not just for current time, but also for duration (which was probably not expected).
