### ISSUE TITLE
Support iOS Dark Mode

### ISSUE THREAD

**Issue by rbackhouse** [rbackhouse/MaximumMPD#31]

**Comment by rbackhouse** [comment]
Available in Version 3.5

**Comment by macmpi** [comment]
my iPhone SEII 13.5.1 is not set with Dark Mode, but sometimes MaximumMPD gets into weird display as per below:
![image](https://user-images.githubusercontent.com/16296055/83973651-3ac3a200-a8e8-11ea-9e27-95c744782a6e.png)

**Comment by rbackhouse** [comment]
Yes this is dynamic update that got missed. A restart of the app should allow it to render correctly. It will be fixed in the next release

**Comment by rbackhouse** [comment]
Hmm it seems that the api I'm dependent on for informing that a dark/light mode change has happened is unreliable. Specifically when suspending and resuming the app it flips mode when the mode has not actually changed

**Comment by macmpi** [comment]
Last update seemingly fixed it, thanks.
