### ISSUE TITLE
Enable loading of Album Art from a HTTP file server

### ISSUE THREAD

**Issue by rbackhouse** [rbackhouse/MaximumMPD#34]

**Comment by rbackhouse** [comment]
Available in version 2.9

**Comment by rbackhouse** [comment]
Need to add support for providing a URL prefix and an alternative album art file name in the configuration

**Comment by rbackhouse** [comment]
Available in Version 3.0

**Comment by mwk1000** [comment]
Can you please add an option or template to use the path of the music file not tag values to find the album art... This is more likely to be accurate and flexible not imposing perfect tags for a set filesystem structure to even work...  I have /raid01/music/<genre>/<subgenra>/<composer>/<artist>/<album>/<disc> all lower case no spaces for unix clean layout the TAGS have Upper/Lower, spaces, special chars <accent grav> etc. I would also be handy to allow non-case sensitive multiple options filenames FOLDER.JPEG / Folder.jpg/ folder.png / Cover.png
