### ISSUE TITLE
create random playlist for genre

### ISSUE THREAD

**Issue by guestguestguestguest** [rbackhouse/MaximumMPD#35]
Would like to be able to select a genre and generate a random playlist restricted to tracks from the chosen genre only.

**Comment by rbackhouse** [comment]
You can do this already. 

On the Settings page there is an option called "Random Playlist by type". If you turn that on and create a random playlist from the Queue page you will be prompted to select the type you want (one of which is "Genre") and the value.

**Comment by guestguestguestguest** [comment]
OK cool... the first time I tried that it didn't work, but it's working now.  Sorry for requesting an existing feature!

F
‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by rbackhouse** [comment]
It could be that the genre name was misspelled. Anyway glad you got it working
