### ISSUE TITLE
Playlists tab: support more formats

### ISSUE THREAD

**Issue by macmpi** [rbackhouse/MaximumMPD#36]
Hi, I'm still on playlist matters...

mpd supports more playlist formats than `.m3u` (while `.m3u` is the default, if no file extension is specified `mpc load` commands):
```
Playlist plugins:
 extm3u m3u pls flac cue embcue
```
Unfortnately, MaximumMPD does not allow to pick anything else than `.m3u` in the Playlists tab: would be nice to have others too ([.pls in particular](https://en.wikipedia.org/wiki/PLS_(file_format))).
_Note:_ FWIW, those playlists have to sit in music directory, not in playlist directory

Thanks!

**Comment by macmpi** [comment]
BTW, in doing so, you may want to review timing info updates (particularly _track duration_) in Playing page.
`.pls` may not promote _track duration_ (some other may not too) so info won't be available in Quueue.
However,`mpc` **does find it out when it starts playing** actual track: so you may fill accordingly in interface, so that seek & al can be used miningfully.
(I had that reported properly once a while, but not reliably on 2.9 version)

**Comment by rbackhouse** [comment]
Currently cue files are supported on the Files screen. I will be adding support for 'pls', 'asx', 'xspf' playlists to. They will show up in file listings and be able to be added to the queue

**Comment by rbackhouse** [comment]
Available now in Version 3.2
