### ISSUE TITLE
Show track names if available on Files screen

### ISSUE THREAD

**Issue by rbackhouse** [rbackhouse/MaximumMPD#38]
Files are shown with actual filenames in Files screen, rather than by their track name (if available).

**Comment by macmpi** [comment]
Just a question: to implement that, do you use data from current mpd database (previously tracked with eventual mpc update/rescan), or do you do any operation that would directly/indirectly physically access the files (well `mpd rescan` would access all files)?
Would be nice if all can be done without accessing them (just rely on mpd database).

**Comment by rbackhouse** [comment]
All interaction with the MPD server is via the published API. It uses the "update" command to pickup any changes that have been made to the MPD database. 

Also I'm going to show the Artist and Album tags along with the Title if available

**Comment by rbackhouse** [comment]
Available now in Version 3.2

**Comment by macmpi** [comment]
Thanks!
Would be nice to have an option to sort by track names then.

**Comment by rbackhouse** [comment]
I've added support for sorting in version 3.3. A top right sort button can be used to switch between sorting by file or by title
