### ISSUE TITLE
Support rescanning of discovered MPD servers

### ISSUE THREAD

**Issue by rbackhouse** [rbackhouse/MaximumMPD#39]
Add an Action Button to the Connections screen to force the zeroconf discovery to be rerun

**Comment by rbackhouse** [comment]
Add an Action Button to the Connections screen to force the zeroconf discovery to be rerun

**Comment by macmpi** [comment]
or a swap-down, like for email refresh en Apple mail? (same philosophy then swap left for server connection)

**Comment by rbackhouse** [comment]
Available in Version 3.0

**Comment by macmpi** [comment]
wow: massive update: thanks.
