### ISSUE TITLE
Files: play single right from list

### ISSUE THREAD

**Issue by macmpi** [rbackhouse/MaximumMPD#42]
Currently, to play a single file, it's a several steps approach: it needs to be added to queue or playlist, then move to other tabs and hits queue reference or load playlist.

Allowing a one-touch direct play single would be really nice & natural for users (like first choice on swipe).
Then, after that single one-shot play, original queue would be restarted with its original status & options (repeat/single/consume, etc).

If users wants more advanced use cases (like current queue/playlist walk-through), then it is still possible

**Comment by rbackhouse** [comment]
This is actually functionality that can be added for Songs as well. 

Doing the save/restore existing queue stuff might be best made configurable.

**Comment by macmpi** [comment]
Understood.
I'm prepping an optimized MPD-based player, and MaximumMPD is a nice UI solution for it (hence all feedback so far). I hope to release soon on Github.
One key feature will be dramatically improved by this.
Thanks!

BTW, if you have a Pi, I can shoot you a pre-built image at some point.

**Comment by macmpi** [comment]
FYI: https://github.com/macmpi/tiny-radioCD

**Comment by rbackhouse** [comment]
Very cool. I'll check it out when I get a chance

**Comment by rbackhouse** [comment]
Sing play without saving current queue is available in version 3.3

**Comment by macmpi** [comment]
Thanks. Saw the red play button on right swipe.
Do you intend to have any special preferences for that usecase (like play once, playlist & player setting restore, ...)?

**Comment by rbackhouse** [comment]
Yes I'm planning to get to that later.

**Comment by macmpi** [comment]
Just a [link](https://github.com/MusicPlayerDaemon/MPD/issues/925) to a related MPD feature request: not sure will gain traction tough.

**Comment by rbackhouse** [comment]
That feature would certainly help supporting play once and restore but I won't hold my breath on that getting added anytime soon.

**Comment by rbackhouse** [comment]
Version 4.3 now in the App store will save and restore the current queue if its not empty after an sutoplay as completed

**Comment by macmpi** [comment]
Thanks, will check soon.
BTW, MPD labelled the request as feature for 0.22!...
May need to be revisited at that time.
