### ISSUE TITLE
Support sorting on relevant screens

### ISSUE THREAD

**Issue by rbackhouse** [rbackhouse/MaximumMPD#43]
1) Support sorting on Files screen. The default currently sorts on file URL. Support sorting on Title too.

2) Support sorting on Browse Albums tab. It currently sorts on Album name. Supportt sort on Artist too.

3) Support sorting on Browse Genres tab -> Songs

**Comment by rbackhouse** [comment]
Available in version 3.3

**Comment by macmpi** [comment]
one thing, sorting preference is reset if you exist view and come back to it.

**Comment by rbackhouse** [comment]
I will add support sorting preferences at some point soon

**Comment by rbackhouse** [comment]
Setting the default sort type is now on the Settings page in Version 3.8
