### ISSUE TITLE
FR: CarPlay support

### ISSUE THREAD

**Issue by kiddigital** [rbackhouse/MaximumMPD#47]
Would be awesome (and probably unique) if CarPlay support would be added.

Especially support for (steering)buttons like Next, Previous, Volume, etc.

Showing the play or queuetab on the car screen is nice.

So, maybe just populate the ‘Now Playing’ screen and react to the Remote Control Events of this screen.

(Yes I use a Pi with MPD in my car for high quality audio input)

**Comment by rbackhouse** [comment]
I can take a look. Not sure there is going be much demand for using it though.

**Comment by rbackhouse** [comment]
I've been looking into adding support for the "Now Playing" Control screen for Apple Watch support and this should also work for CarPlay too. I prefer this approach as it means I don't have to jump through the hoops of registering as a specific CarPlay app.
