### ISSUE TITLE
Support showing current Play information in the NowPlayingInfoCenter

### ISSUE THREAD

**Issue by rbackhouse** [rbackhouse/MaximumMPD#49]

**Comment by kiddigital** [comment]
Does this include responding to the basic button Play, Pause, Next, Prev? So basic control or does this require additional things?

But already fan of this new feature 😃

**Comment by rbackhouse** [comment]
Yes it should do those things in addition to showing the current song/artist/album playing. I'm hoping I can hook into managing volume too.

**Comment by kiddigital** [comment]
Noticed the release of the new version including this feature. Not able to test it if it works for Carplay (and AppleWatch) on a very short term (holidays :) ) but will test it asap (in about two weeks) and report back. Already thanks for work to add this feature

**Comment by rbackhouse** [comment]
I've tested quite a bit on AppleWatch and a little with carplay. I still could not get the cars volume control to work though

**Comment by kiddigital** [comment]
> ... I still could not get the cars volume control to work though

Hm.. maybe that makes sense assuming that the volume control is somehow directly connected to the car amplifier. For my use-case not an issue at all as I am controlling volume of my separate amplifier independently of the steering wheel volume controls anyway :) Looking forward to using this new feature a lot during my car rides.

**Comment by rbackhouse** [comment]
Fixing 1) should not be difficult.

For 2) things are bit more complex. I have occasionally the behavior you describe but have not been able to figure out the pattern that triggers it. The app update the now playing data every second. The problem is that there is no returned status to indicate if the update was successful.
