### ISSUE TITLE
Song ratings

### ISSUE THREAD

**Issue by boblund** [rbackhouse/MaximumMPD#50]
Thanks for making MaxiumMPD - it's pretty much what I've been looking for to replace iTunes remote for forked-daapd. Is there a way to set song ratings that I'm not seeing.

**Comment by rbackhouse** [comment]
There is no support for song ratings. Doing some research on how some other MPD clients have supported this show that they use MPD stickers (https://www.musicpd.org/doc/html/protocol.html#stickers) although there is no official definition on sticker names to be used. I'm hesitant to add support for something that seems too vague.

**Comment by nemethf** [comment]
I personally don't need this feature, but I was curious about sticker usage.  It seems there are some sticker names that are used consistently by several clients: https://github.com/jcorporation/mpd-stickers
