### ISSUE TITLE
random playlist hangs app

### ISSUE THREAD

**Issue by guestguestguestguest** [rbackhouse/MaximumMPD#52]
Selecting 'Random Playlist' from the Play screen hangs the app.  Tried with items in the queue, and with an empty queue, hangs in both cases.  Maximum MPD version 4.0 on iOS 13.6

**Comment by rbackhouse** [comment]
How many songs in your Music DB and how performant is your MPD server ?
It's possible that its running ok but taking an awful long time to complete, especially if you have a large DB.

**Comment by guestguestguestguest** [comment]
$ mpc stats
Artists: 1454
Albums: 2562
Songs: 33054

Running mpd 0.21.23 on raspberry pi

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by rbackhouse** [comment]
I think the the combination of the number of songs and that you are running on a pi is probably the problem. The random playlist code is really old and was never going to run well with large databases. 

I think there are some improvements to the MPD API that might help here but this will only work with newer versions of MPD

**Comment by guestguestguestguest** [comment]
Disappointing, mainly because this feature used to work. I checked the NEWS files [change log] for the two newer versions of mpd and I don't see anything that looks relevant to this issue. Oh well... I could try deleting a bunch of files to see if it works again, but that seems like killing the patient in order to save him, or some such aphorism.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by rbackhouse** [comment]
Well that's very strange then if it used to work. I've not changed that code in a very long time. 

No need to delete stuff from your db. I should be able to had a better version that will run with 0.21 and 0.20 MPD versions. Anything older will probably have to stick with the original code though.

**Comment by rbackhouse** [comment]
Version 4.1 in the App store has the new random playlist code

**Comment by guestguestguestguest** [comment]
Richard,

Random Playlist on the 'Playing' screen works again in v4.1. Thanks much for the new code. Generating random playlists from the Queue screen [by Artist or Genre etc] still spins forever, but the app doesn't hang. Just no playlist.

Frank/guestguestguestguest
/guestguestguestguest

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by rbackhouse** [comment]
The new random playlist code is only used when "By Type" is turned off. That would explain why it works on the Play screen and not on the Queue screen if you have "By Type" enabled.

If it still just spinning then that would suggest the results of a search by type is returning info that the app does not like. 

I'm guessing that maybe you have added new music to your DB ?

Is it only by Artist or Genre that fails or for all types ?

**Comment by guestguestguestguest** [comment]
The spinning with no result happens for all types: artist, album, title and genre. The queue is emptied and no playlist is created. When I disable 'Random playlist by type' in settings, it works fine.

I add music to my database often. Is there a way, maybe via debugging, to see what data the app is choking on?

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by rbackhouse** [comment]
I think I have asked you to debug before using the debug option at the bottom of the settings screen.
The command used for random by type is 

search <type> "<type value>"

For example 

search genre "alt"

or 

search artist "new order"

You should see the results listed below

The results are also written to a file that you can access via the Files iOS app. It can be found in the "On My iPhone" location in the MaximumMPD ditrectory. Its called "mpddebug.json"

If the command actually runs fine then the results will hopefully help indicate what is causing the problem

**Comment by guestguestguestguest** [comment]
OK, please close this issue. Random by type works fine, my problem was "user error" -- I was leaving the value field blank.

Sorry for wasting your time on this. Thanks for your attention & good work.

Frank

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by rbackhouse** [comment]
Glad you figured it out. Revisiting the old random code was well overdue so no wasting of time
