### ISSUE TITLE
Make number of Grid View columns configurable

### ISSUE THREAD

**Issue by rbackhouse** [rbackhouse/MaximumMPD#57]
For iPads the options are 2,3,4,5,6 columns
For iPhones the options are 2,3,4

**Comment by KokonZhang** [comment]
Great to see this enhancement is coming

**Comment by rbackhouse** [comment]
Available in Version 4.2

**Comment by KokonZhang** [comment]
great. Thanks fir for your effort.

发自我的iPhone
