### ISSUE TITLE
No defaults for Unknown Album in Browse tab

### ISSUE THREAD

**Issue by tweelix** [rbackhouse/MaximumMPD#58]
If a file has, for example, Artist information, but not album information, clicking on said artist in the Browse tab will show no Albums, therefore no songs. 
Would it be possible to add a default 'Unknown Album' category much like iTunes does?

**Comment by rbackhouse** [comment]
This should be doable. All songs without an album tag for a given artist will be associated with an album called "Unknown"

**Comment by rbackhouse** [comment]
This support will (for now at least) only be available when connected to MPD servers version 0.21 or greater

**Comment by rbackhouse** [comment]
Available in Version 4.4 in the App Store
