### ISSUE TITLE
Default sort order of album tracks

### ISSUE THREAD

**Issue by nellistc** [rbackhouse/MaximumMPD#61]
Hello,

By default, the app is sorting album tracks by title name. If there's any combination of settings that will make it sort by track number, I can't find it.

Using the sort button in the top right, it takes two taps to switch to track number ordering - as if the app believes it's in track order already. From then on, it's one tap to switch between title and track number.

I'm on v4.4, connected to a local forked-daapd instance.

Thanks for your hard work!

**Comment by rbackhouse** [comment]
I suspect this might be because forked-daapd defaults to a difference return order for songs than MPD. All my MPD servers return songs ordered by track. I think the fix will be to explicitly sort by track when the songs are returned and hopefully that will fix the problem

**Comment by nellistc** [comment]
Ok, let me know if you would like any further testing. There's no option in forked-daapd that I'm aware of to modify the sort order for MPD clients.

**Comment by rbackhouse** [comment]
I just tried with a forked-daapd server and as I suspected the default sort is on the Track name. I can fix by just adding a sort on the returned song list.

**Comment by rbackhouse** [comment]
Fixed in version 4.6 in the App Store.
