### ISSUE TITLE
Save and restore repeat and consume settings when single song Play Now used

### ISSUE THREAD

**Issue by macmpi** [rbackhouse/MaximumMPD#65]
see screenshot.
no error on the second try
![image](https://user-images.githubusercontent.com/16296055/106363580-96d0b000-6329-11eb-91ab-615c6d53ea7d.png)

**Comment by rbackhouse** [comment]
Are you able to create playlists manually on this MPD server ? This seems to indicate that the configured playlist directory does not have write permissions setup for the userid running MPD

**Comment by macmpi** [comment]
Good catch indeed, playlist directory was not set to mpd user.

Play single file scenario may need to handle repeat mode (and consume).
For instance if repeat is set (like permanent Radio playlist that does not consume and can circle back), playing a single file will loop endlessly on it.

**Comment by rbackhouse** [comment]
So do you mean that save/restore existing queue should be disabled when Repeat and/or Consume are enabled ?

**Comment by macmpi** [comment]
Not really.
The app may need to store current Repeat and Consume status, then set no repeat & consume to play single file, then reset playlist and previously stored Repeat & Consume status.
Would it make sense?

**Comment by rbackhouse** [comment]
Yes, that makes sense

**Comment by rbackhouse** [comment]
Save and restore repeat and consume settings now available in Version 4.7
