### ISSUE TITLE
IOS - Speaker noise while using MaximumMPD

### ISSUE THREAD

**Issue by tonymartino** [rbackhouse/MaximumMPD#67]
Greetings,

New user here and I'm enjoying the app however, I have noticed a problem. When using MaximumMPD to control my MPD server, the iPhone's speakers begin to play a low white noise. If I switch to the home screen or another app, the noise stops and it resumes if I switch back to MaximumMPD.  

This is an iPhone XR running IOS 14.4.2. Any idea what might be happening?

**Comment by rbackhouse** [comment]
Its a problem with the "Now Playing Control" support. You can work around it for now by turning off "Use Now Playing Control" on the setting page

**Comment by tonymartino** [comment]
Worked-around! Thanks for the quick response.

**Comment by rbackhouse** [comment]
Fixed in Version 4.8
