### ISSUE TITLE
No Audio Output

### ISSUE THREAD

**Issue by aflyingpumpkin** [rbackhouse/MaximumMPD#69]
I have not been able to get the application to output audio. I currently have my MPD configuration output audio to an http stream which I can open while in an app like vlc media player. But when I open up MaximumMPD it stops playing the audio. I also cannot connect to the HTTP audio stream in the application.

**Comment by rbackhouse** [comment]
If you turn "Link Device Volume Control to MPD Volume" off on the settings page then audio output from other apps should not be affected. 

MaximumMPD does not currently support audio streaming.
