### ISSUE TITLE
Wrong Artist can be listed when browsing Albums

### ISSUE THREAD

**Issue by rbackhouse** [rbackhouse/MaximumMPD#7]
Wrong Artist can be listed when browsing Albums

**Comment by rbackhouse** [comment]
@guestguestguestguest 

I have not been able to track this down yet, however I have just released a new version that provides a way to debug MPD commands. If I can get you to run the list albums commands and send me the results I should be able to figure out the problem.

The cmd is "list album group artist"
The debug functionality can be found at the bottom of the Settings Page
1) Click the Debug link and you should see a page with an Entry Field at the top for the command
2) Enter "list album group artist" in the entry field and click the Run button in the floating ActionButton
3) You should see the results listed below

The results are also written to a file that you can access via the Files iOS app. It can be found in the "On My iPhone" location in the MaximumMPD ditrectory. Its called "mpddebug" and you should be able to select it and send it to me.

**Comment by guestguestguestguest** [comment]
Thanks for keeping on this one, Richard.  I ran the cmd you asked for, and have attached the mpddebug file and screenshot of buggy albums list.

Frank

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by rbackhouse** [comment]
Not seeing any attachments. You might have to direct email them to me at richardabackhouse@gmail.com

**Comment by rbackhouse** [comment]
Fixed in Version 1.7

**Comment by guestguestguestguest** [comment]
Looks good Richard, thanks!

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
