### ISSUE TITLE
App will not start on an old Ipad

### ISSUE THREAD

**Issue by tkgafs** [rbackhouse/MaximumMPD#70]
Hello,

I have recently been given an old Ipad (3rd generation) which is running IOS 9.3.6

I have installed MaximumMPD from app store but I am unable to get it to start

The app appears full screen then disapears

I tried downloading the android version onto my phone and it gives me a configuration screen where I can add my mpd server and it works successfully

As I havent used apple kit before am i doing something wrong or is there a problem with the app

**Comment by rbackhouse** [comment]
I don't there is going to be much i can do about this. iOS 9 is really old. We are now on iOS 14.6 The oldest simulator I can get back to for testing is iOS 11. 4 based.

**Comment by tkgafs** [comment]
No problem I rather thought that would be the case.As I said I've never used apple stuff before and didn't know if I was missing a step somewhereBest wishesTimOn 1 Jun 2021 12:43, Richard Backhouse ***@***.***> wrote:
I don't there is going to be much i can do about this. iOS 9 is really old. We are now on iOS 14.6 The oldest simulator I can get back to for testing is iOS 11. 4 based.
