### ISSUE TITLE
playlist delete doesn't work

### ISSUE THREAD

**Issue by guestguestguestguest** [rbackhouse/MaximumMPD#71]
From Play menu, Playlists tab, select a playlist.  From the list of tracks, press the trash icon to delete a track.  Nothing happens.  Expected behavior: the track gets deleted from the playlist.

**Comment by rbackhouse** [comment]
This somehow got missed a while back. A click should load an action sheet with two options 

1) Delete playlist entry
2) Goto the Album that contains the playlist entry

A fix is available in version 4.9 in the App Store

**Comment by guestguestguestguest** [comment]
Fixed! Thanks much Richard.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
