### ISSUE TITLE
Now way to stream

### ISSUE THREAD

**Issue by jtgd** [rbackhouse/MaximumMPD#74]
Streaming is mentioned, "Support streaming from URLs", but there is nothing in the user interface to do this.
If it is actually possible then it should be more clear how to do this.

**Comment by rbackhouse** [comment]
I had started on adding support for connecting to UPnP devices that would allow streaming to the device itself. It's not complete yet. When it is there will be details available on how to use it

**Comment by jtgd** [comment]
I'm puzzled why you would involve UPnP. 
mpd doesn't have an output for UPnP.  
It does output to HTTP and can be played by an ordinary browser with HTML5. Seems easier.

It would be nice to model the behavior of MPD Remote on Android.
https://play.google.com/store/apps/details?id=net.prezz.mpr

**Comment by rbackhouse** [comment]
Streaming via the MPD httpd plugin is generally discouraged. UPnP is a much more reliable protocol for this. I already have support for UPnP added to load album art when available. 
There are numerous media apps out there that support both MPD and UPnP

**Comment by jtgd** [comment]
There may be apps that support both, but they are two different worlds. MPD does nothing with UPnP and UPnP does nothing with MPD. I'm not sure who is discouraging it but streaming from HTTP works for me - all day every day. How you write your app is up to you but that still leaves us with nothing for iPhone that controls MPD and streams from it.
