### ISSUE TITLE
HTTP album art from actual music file PATH

### ISSUE THREAD

**Issue by mwk1000** [rbackhouse/MaximumMPD#78]
Can you please add an option or template to use the path of the music file not tag values to find the album art... This is more likely to be accurate and flexible not imposing perfect tags for a set filesystem structure to even work... I have /raid01/music////// for unix clean layout the TAGS have Upper/Lower, spaces, special chars etc. I would also be handy to allow non-case sensitive multiple options filenames FOLDER.JPEG / Folder.jpg/ folder.png / Cover.png

Example:
/raid01/Music/Classical/Bach/Bach - Complete Edition/V01/CD1/folder.jpg

I cant figure out how this path ( and 30000 more like it ) will be found with the settings offered. Simple fix use the current playing music file path. Thx

**Comment by rbackhouse** [comment]
Assuming I'm understanding what you are requesting correctly then this will only work well if the artist directory name and album directory name match the artist and album tags in the songs files. 

This is because the browse functionality uses tags to find and load artist/albums/songs and that is where the albumart images are loaded and visible.

**Comment by mwk1000** [comment]
That is an accurate description of the PROBLEM... So as my example shows I never get album images. From a practical standpoint using the actual path of the media files to locate the cover image would seem ( to me ) to be far more reliable and completely independent of tagging choices ...

**Comment by rbackhouse** [comment]
I think the current code might be working closer to want you want than you realize. Its just its not documented very well how the Album Art URL is assembled.

Using your example

/raid01/Music/Classical/Bach/Bach - Complete Edition/V01/CD1/folder.jpg

Assuming your MPD servers db is rooted at "/raid01/Music" then the resolved path (its resolved from the FILE metadata returned for songs in the Album) used in the URL will be

"/Classical/Bach/Bach - Complete Edition/V01/CD1/"

The full URL would be 

http://[IP address of HTTP server]:[Configured HTTP Port]/Classical/Bach/Bach - Complete Edition/V01/CD1/folder.jpg

(The Album Art Filename config option would need to set to "folder.jpg")

This would assume you HTTP server is serving from the "/raid01/Music" directory

Whats missing is the ability to have multiple options for the image filename.

It should be possible to add an addition MPD API call to search for these multiple options. The downside is that it would be an additional MPD API call per album.

I can look into adding that functionality

**Comment by rbackhouse** [comment]
Enabling "Search for Image File" in the Album Art HTTP setting will enable the search for album art image files (cover.jpg/png and folder.jpg/png all cases) in each album directory. Note: selecting this option will be slower as each directory search is an addition MPD API call.
Available in 5.2

**Comment by mwk1000** [comment]
OK that is close , and easy to check , I will add another apache alias setting /raid01/Music as the root Thanks much for looking

**Comment by mwk1000** [comment]
Tested,  but I see the unexpected, this is trying to cache EVERY album cover in the database ? I am used to seeing them retrieved as the file /album plays... ( other players ) 
Tracking the apache access log I do see some 200 success codes ( just the folder.jpg) option selected and many 404 ( wrong name ) codes so the path problem is OK... 
However this has little practical chance of working for a large collection  , The space used on my ipad will be huge , the time required to get the whole collection will be hours .... , days if I enable search ...

**Comment by rbackhouse** [comment]
The origins of AlbumArt support  started with using the MPD Album Art API. Its performance is insufficient to use with on demand downloading. I added HTTP support as an alternative for filling the local cache. The downloads work in background while connected.

What do you consider a large collection ? I have 1100 albums in my main db and that results in 500mb of cache usage for me.  I don't consider that a problem unless you are talking 10 of 1000's of albums. 

Details on all album art usage can be found on the help page https://rbackhouse.github.io/MaximumMPD.html. You can get to it from the About page in the app.

I can look into adding an option for on demand loading via http

**Comment by mwk1000** [comment]
I have 2500 albums and ~ 35K songs, I do not want to NEED over a GB of storage that is essentially wasted , while I may have the space on an IPAD I do not on my phone where I would prefer to store books, or actual music for travelling... I guess my perspective is it a computational time and space activity that serves no useful purpose over simply fetching on demand. What triggers a reload ? I I make changes to a few files does it rescan only the changed ? I stopped at 200MB but it had failed twice and I had to turn the feature off/on to resume. So do I get a product that I pick up pick a song and play, with art or am I missing the art , need to refresh the art, etc. I understand if this is not a simple fix and that's ok your app your call. But fetching on demand is always the latest version , no maintenance, only requires maybe 10-20 images ( whatever the number it's no where close to 2500 ) per session , 0 added storage .... Never misses because it is still not downloaded, i no longer need to care about preloading/reloading. So I think it would be a better experience but there may not be enough demand to warrant the work ... So my 2cents. But it does not change my respect that you are even having the conversation ! Cheers

**Comment by rbackhouse** [comment]
I get where you are coming from. In all honestly I have never really been bothered with using album art but other users of the app have. When MPD itself added an Album Art API i added support and then later people asked for HTTP file serving support.

I'm always open to adding features people request if they are feasible and make sense. As I have now added code to be able to resolve if an album art file exists for an album I can also support an alternative of caching the URL instead of the image itself. This would solve your reload/update requirement as long as the file name stays the same. There still needs to be the initial parse of all albums to search for image files, and this involves an MPD API call per album. This will take some time to complete initially depending on the number of albums you have in your collection.

**Comment by rbackhouse** [comment]
Option to save path instead of image has been added to version 5.3
