### ISSUE TITLE
tried to build ipa file for running on xcode

### ISSUE THREAD

**Issue by ibmbea** [rbackhouse/MaximumMPD#79]
but i got the xconfig not found error,

/Users/xxx/Downloads/MaximumMPD-master/ios/Pods/Target Support Files/Pods-MaximumMPD/Pods-MaximumMPD.release.xcconfig: unable to open file (in target "MaximumMPD" in project "MaximumMPD")

tried pod install under folder ios. but got 

[!] No podspec found for `CocoaUPnP` in `../../CocoaUPnP/CocoaUPnP.podspec`

how to resolve it?

**Comment by rbackhouse** [comment]
You need to download https://github.com/arcam/CocoaUPnP and place it as a peer directory to MaximumMPD
