### ISSUE TITLE
date search feature request

### ISSUE THREAD

**Issue by guestguestguestguest** [rbackhouse/MaximumMPD#81]
Hi Richard,

I would like to be able to search the database for all albums released in 1972 (or other specified year).  MaximumMPD's search feature doesn't seem to support this.

Would this be a reasonable feature to implement?

Thank you for your attention.
Frank

**Comment by rbackhouse** [comment]
Currently search only looks at the artist, album, and title values. I can add the date tag to be checked too

**Comment by rbackhouse** [comment]
Fix is available in version 5.4

**Comment by guestguestguestguest** [comment]
Thanks it works great.

F
‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
