### ISSUE TITLE
volume level not updated

### ISSUE THREAD

**Issue by macmpi** [rbackhouse/MaximumMPD#91]
It seems volume level UI feedback is not updated if `mpd` server is updated by another `mpc` client.
(maybe some other UI elements too, in similar situations)

**Comment by rbackhouse** [comment]
This should be working. The current volume value is checked and updated in the UI on via continuous status check call run ever second while a song is playing and every 30 seconds otherwise. I'll test and see if this still works

**Comment by macmpi** [comment]
I confirm after waiting longer.
Scenario: `mpd` server (0.23.5) is playing an internet web radio; playback is initiated by another `mpc` client.
UI does show track info and playback time progressing, play-pause button is also accurate (and updated if changed from other `mpc` client).
However volume bar is not updated.

**Comment by rbackhouse** [comment]
Can confirm that this is broken

**Comment by macmpi** [comment]
Actually even playing track names may get out of sync.
`mpd` protocol has evolved a bit lately (and official `mpc` followed that).
It seems your app is talking directly to `mpd`, not using a local official `mpc` app to do the communication thing, right?
If so, it may be subject to protocol changes more than if using official `mpc` I guess.

**Comment by rbackhouse** [comment]
Did you mean to leave this comment for volume issues or was it meant for #76 ?

**Comment by macmpi** [comment]
I agree the play-now part is fundamentally related to https://github.com/rbackhouse/MaximumMPD/issues/76 , although the symptom (track not cleared) is new.
I thought the 4 "out of sync" issues (volume sync, track name sync, track not cleared in playlist, repeat status) may be related to some common root cause such as protocol changes or sth...

**Comment by rbackhouse** [comment]
The volume issue was simply not updating the ui control when the volume level changed.

**Comment by rbackhouse** [comment]
Fixed in version 5.5 now in the App Stores
