### ISSUE TITLE
web radio in playlist: display current playing title if avail

### ISSUE THREAD

**Issue by macmpi** [rbackhouse/MaximumMPD#92]
I have a .m3u playlist with webradios as follows:
```
#EXTM3U

#EXTINF:-1, Radio Paradise - Main Mix
http://stream.radioparadise.com/aac-128

#EXTINF:-1, TSF Jazz - Direct
http://tsfjazz.ice.infomaniak.ch:80/tsfjazz-high
```

Main playback window does show currently playing stream fine, but lacks currently playing title if stream does provide it.
Typical case is with Radio Paradise.
Standard console `mpc` client does return current title, but MaximumMPD does not show it: would be nice addition.
Thanks!

**Comment by rbackhouse** [comment]
It appears the problem is that the "name" tag is overriding the "title" tag where is should be the opposite

**Comment by rbackhouse** [comment]
Fixed in version 5.5 now in the App Stores

**Comment by macmpi** [comment]
Thanks.
However the stream name is now omitted, and keeping it in addition to track title would be great to remember which item name (like radio station) we are playing in playlist.
Makes sense?

**Comment by rbackhouse** [comment]
The problem is that currently the Play screen has no knowledge that its a url stream. It takes the "artist" and "album" tag from the current song, use "title" or "name" if "title is not present and then formats a time value. 

If there is a protocol to follow for the streams i could use the stream name is one of the other values but it seems they vary quite a bit.

**Comment by macmpi** [comment]
To illustrate my point:
command-line MPD does report stream name and currently playing title
```
$ mpc
Radio Paradise (128k aac): Cracker - The Golden Age
[playing] #7/8   0:34/0:00 (0%)
volume:100%   repeat: on    random: off   single: off   consume: off

```
while MaximuMPD only shows:
![image](https://user-images.githubusercontent.com/16296055/184887268-e21d58f4-63e4-4625-8fce-49cf03fcfd4e.png)

**Comment by rbackhouse** [comment]
I'm looking to identify streaming source by checking that the file value starts with "http://". I've only ever seem the URLs be "http" based. 
Are there streams that are also "https" based?

**Comment by macmpi** [comment]
Hi,
yes there are:
https://stream.rfm.fr/rfm-wr14.aac
BBC Radio 1 UK as per http://fmstream.org/index.php
...

**Comment by macmpi** [comment]
:+1: Thanks

**Comment by macmpi** [comment]
on bit though: sometimes those titles may be a quite long line which may not fit (has ...): any chance it could gently scroll in playing view, so that all may be read?

**Comment by rbackhouse** [comment]
I created https://github.com/rbackhouse/MaximumMPD/issues/97 to tackle that
