### ISSUE TITLE
Shortcut integration 

### ISSUE THREAD

**Issue by JoFreHe** [rbackhouse/MaximumMPD#94]
I wish the App would be integrated in the Apple shortcut system. That you can automate when songs or playlist are played.

**Comment by rbackhouse** [comment]
While MaximumMPD does not support shortcuts directly it does indirectly via Universal Links. You can add link URLs to perform play state actions and create shortcuts from them via the Web-> URL category. 

The following links are supported 

maximummpd://playpause
maximummpd://stop
maximummpd://next
maximummpd://previous

Use these as URL values
