### ISSUE TITLE
browse genre albums list bug?

### ISSUE THREAD

**Issue by guestguestguestguest** [rbackhouse/MaximumMPD#95]
From the browse screen, Genres tab, when I list albums for the Folk genre, the album Blue by the artist The Jesus Lizard appears on the list.  The genre for this album is actually 'Rock'.  What's interesting is, there is another album with the same name (Blue) by artist Joni Mitchell, which has the genre folk.  This is the one which should appear in the albums list for Folk... but it's not there.  Instead MaximumMPD is listing the other one.  I'm runnnig version 5.5 on iOS.

**Comment by rbackhouse** [comment]
Do you happen to know the version of your MPD server.

**Comment by guestguestguestguest** [comment]
0.21.23

Admittedly a bit old, it's just a pain to update and it works fine.
------- Original Message -------

**Comment by rbackhouse** [comment]
Should be fixed in version 5.6 that is now available

**Comment by guestguestguestguest** [comment]
Thanks Richard, the new version is working properly now.

Frank
------- Original Message -------
